name: plough
description: "Flutter package to render interactive network graph visualizations, featuring multiple layout algorithms, customizable appearance."
version: 0.7.0
homepage: https://github.com/szktty/plough
license: Apache-2.0

screenshots:
  - description: "plough layout"
    path: screenshots/manual_layout.png

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  fast_immutable_collections: ^11.0.0
  flame: ^1.23.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  http: ^1.1.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  uuid: ^4.5.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  golden_toolkit: ^0.15.0
  json_serializable: ^6.8.0
  test: ^1.25.7
  very_good_analysis: ^10.0.0

flutter:
