name: Build

on:
  push:
    branches: [ "main", "develop", "feature/ci" ]
  pull_request:
    branches: [ "main", "develop", "feature/ci" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - name: Install Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev
      - run: dart format --set-exit-if-changed .
      - run: cd example && flutter build linux --debug --no-color